server:
  hosts:
    - <rabbit-host-1>
    - <rabbit-host-2>
    - <rabbit-host-3>
  username: ${RABBIT_USERNAME}
  password: ${RABBIT_PASSWORD}
scaler:
  # deployment_name:
  #   minPod: default = 0 if not set
  #   maxPod:
  #   vHost:
  #   interval: time between 2 scraping or time of init worker
  #   accumulative_limit: number of pods of every scale default = 1 if not set
  #   queues: list of queues
  #   ttl: time of processing message default is 1.0 (m) if not set

  deoloyment-1:
    minPod: 0
    maxPod: 10
    vHost: test
    interval: 120
    accumulative_limit: 2
    ttl: 3.0
    queues:
      - queue1
      - queue2
      - queue3
